name: AWS CodeArtifact Badge Update  (Only on Manual Run)🚀

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip -o awscliv2.zip
           sudo ./aws/install --update
         
      - name: Set AWS Region
        run: |
          aws configure set region ap-south-1   
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    

      - name: Get Latest Version from CodeArtifact
        id: get_version
        run: |
             VERSION=$(aws codeartifact list-package-versions \
                --domain sanjeet-registry \
                --repository my-npm-private \
                --format npm \
                --package 'hello-package' \
                --namespace 'my-scope' \
                --status Published \
                --query "versions[*].version" \
                --output json | jq -r '.[]' | sort -V | tail -n 1)
              
              echo "VERSION=$VERSION" >> $GITHUB_ENV

         
      - name: Fetch and update version.json with latest version
        run: |
         echo '{
            "schemaVersion": 1,
            "label": "AWS CodeArtifact",
            "message": "'${VERSION}'",
            "color": "green"
          }' > version.json
        
      - name: Update README.md with Latest Version Badge
        run: |
           sed -i "s/AWS%20CodeArtifact-v[0-9]*\.[0-9]*\.[0-9]*/AWS%20CodeArtifact-v${VERSION}/g" README.md
          

          
      - name: Add changes
        run: |
          git add .
          git status    

      - name: Commit Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git commit -m "🔖 chore: update AWS CodeArtifact badge with version '${VERSION}' 🚀" || echo "No changes to commit"
          
      - name: Debug GitHub Token and PAT Token
        run: |
          echo "GitHub Token Length: ${#GITHUB_TOKEN}"
          echo "PAT Token Length: ${#PAT_TOKEN}"
          echo "Repository: ${{ github.repository }}"
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    
         
      - name: Push changes to GitHub
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
           git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
           git push origin HEAD:main

      - name: Push changes to GitHub
        if: false  # ❌ This step is always skipped!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main